dah/urls.py
from django.conf import settings
from django.conf.urls.static import static

import dah.views


from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('__reload__/', include('django_browser_reload.urls')),
    path('', dah.views.landing, name='landing'),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path

import dashboard.views as views

app_name = 'dashboard'
urlpatterns = [
    path('', views.list, name='list'),
    path('<int:pk>/', views.list, name='list_with_id'),
    path('detail/<int:pk>/', views.detail, name='detail'),
]

dashboard/models.py
from django.db import models

# Create your models here.


class Post(models.Model):
    title = models.CharField('제목', max_length=100)
    description = models.TextField('설명')
    body = models.TextField('본문')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

dashboard/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'description',
            'body',
        ]

dah/views.py
from django.shortcuts import render


def landing(request):
    return render(request, 'landing.html', {})

dashboard/views.py
from django.shortcuts import render, get_object_or_404

from .models import Post

from dashboard.forms import PostForm


def list(request, pk=None):
    context = {}
    posts = Post.objects.all().order_by('-created_at')

    if request.method == 'POST':
        form = PostForm(request.POST or None)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            description = form.cleaned_data.get('description')
            body = form.cleaned_data.get('body')

            Post.objects.create(title=title, description=description, body=body)

    elif request.method == 'DELETE':
        post = get_object_or_404(Post, pk=pk)
        post.delete()

        return render(request, 'dashboard/post_list.html', {'posts': posts})

    else:
        form = PostForm()

    context['form'] = form
    context['posts'] = posts

    return render(request, 'dashboard/post_list.html', context)


def detail(request, pk=None):
    post = Post.objects.get(id=pk)

    return render(request, 'dashboard/post_detail.html', {'post': post})

dashboard/templates/dashboard/post_detail.html
{% extends 'scaffoldings/base.html' %} {% block contents %}
<title>{{ post.title }}</title>
<body>
  <h1 class="text-6xl font-bold">{{ post.title }}</h1>
  <p class="text-slate-400">{{ post.description }}</p>
  <p>{{ post.body }}</p>
  <a href="{% url 'dashboard:list' %}">목록으로 돌아가기</a>
</body>
{% endblock %}

dashboard/templates/dashboard/post_list.html
{% extends 'scaffoldings/base.html' %} {% block contents %}
<title>게시판</title>

<body>
  <div id="post-list">
    <div class="flex flex-col space-y-12">
      <h1 class="text-4xl font-bold">게시글 목록</h1>
      <ul x-data="{ openIndex: null }" class="p-2">
        {% for post in posts %}
        <div class="flex">
          <a href="{% url 'dashboard:detail' post.id %}">
          <div class="flex flex-row items-center justify-between p-2 my-2 border rounded">
              <div class="flex flex-col items-center justify-center min-h-12">
                <li
                  class="text-xl font-semibold cursor-pointer"
                  @click="openIndex = openIndex === {{ post.id }} ? null : {{ post.id }}"
                >
                  {{ post.title }}
                </li>
                <li x-show="openIndex === {{ post.id }}" x-transition.scale>
                  {{ post.body }}
                </li>
              </div>
            </div>
          </a>
          <button
            hx-delete="{% url 'dashboard:list_with_id' post.id %}"
            hx-target="#post-list"
            hx-confirm="Are you sure?"
            hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
            class="p-2 text-white bg-red-500 border rounded">
            제거
          </button>
        </div>
        {% empty %}
          <li>게시글이 없습니다.</li>
        {% endfor %}
      </ul>
    </div>
    <div class="mt-12">
      <form
        hx-post="{% url 'dashboard:list' %}"
        hx-target="#post-list"
        class="flex flex-col space-y-4"
      >
        {% csrf_token %}
        <input id="title" type="text" name="title" placeholder="제목 입력" />
        <textarea name="description" placeholder="설명 입력"></textarea>
        <textarea name="body" placeholder="내용 입력"></textarea>
        <button type="submit" class="px-4 py-2 text-white border rounded bg-slate-300">게시글 작성</button>
      </form>
    </div>
  <div>
</body>

<script>
function getCookie(name) {
  let cookieValue;

  if (document.cookie && document.cookie !== "") {
    const cookies = document.cookie.split(";");
    for (let i = 0; i < cookies.length; i++) {
      const cookie = cookies[i].trim();

      if (cookie.substring(0, name.length + 1) === (name + "=")) {
        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
        break;
      }
    }
  }

  return cookieValue;
}
</script>
{% endblock %}

theme/templates/landing.html
{% extends 'scaffoldings/base.html' %} {% block contents %}
<div class="flex flex-col items-center space-y-12">
  <h1 class="text-5xl font-bold">DHA Dashboard</h1>
  <div @foo="console.log('foo was dispatched')">
    <button @click="$dispatch('foo')">foo</button>
  </div>
  <button
    class="px-4 py-2 font-bold text-white bg-black border rounded hover:bg-slate-300"
  >
    클릭
  </button>
</div>
{% endblock %}

theme/templates/scaffoldings/base.html
{% load static tailwind_tags django_browser_reload%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Django + Alpine.js + HTMX 게시판</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <script
      defer
      src="https://cdn.jsdelivr.net/npm/alpinejs@3.13.7/dist/cdn.min.js"
    ></script>
    <script
      src="https://unpkg.com/htmx.org@1.9.11"
      integrity="sha384-0gxUXCCR8yv9FM2b+U3FDbsKthCI66oH5IA9fHppQq9DDMHuMauqq1ZHBpJxQ0J0"
      crossorigin="anonymous"
    ></script>

    {% tailwind_css %}
  </head>

  <body class="flex items-center justify-center bg-gray-50">
    <div class="">
      <section class="">
        <main>{% block contents %}{% endblock %}</main>
      </section>
    </div>
  </body>
</html>